local Common = {}

Common["NoobiniPizzanini"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://71606418170750",

	AnimationIds = {
		Idle = "rbxassetid://113005956942330",
	},
}

Common["TimCheese"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://113029366638482",

	AnimationIds = {
		Idle = "rbxassetid://83370059939481",
	},
}

Common["LiriliLarila"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://89008368620221",

	AnimationIds = {
		Idle = "rbxassetid://103192330142474",
	},
}

Common["FluriFlura"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://103695140537567",

	AnimationIds = {
		Idle = "rbxassetid://77592251144314",
	},
}

Common["KiwiPipi"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://77497252012744",

	AnimationIds = {
		Idle = "rbxassetid://109504844715349",
	},
}

Common["Svinino"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://83119535216667",

	AnimationIds = {
		Idle = "rbxassetid://77895533680662",
	},
}

Common["MelonOtter"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://119865150419102",

	AnimationIds = {
		Idle = "rbxassetid://78570754226359",
	},
}

Common["KiwiBird"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://75083833944999",

	AnimationIds = {
		Idle = "rbxassetid://123992322727377",
	},
}

Common["SickPenguin"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://70810466174755",

	AnimationIds = {
		Idle = "rbxassetid://83602497955243",
	},
}

Common["JobApplication"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://92046509880592",

	AnimationIds = {
		Idle = "rbxassetid://132985846821600",
	},
}

Common["PipeMan"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://134349231323811",

	AnimationIds = {
		Idle = "rbxassetid://117236878782608",
	},
}

Common["Dolphinita"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://127265047725576",

	AnimationIds = {
		Idle = "rbxassetid://77930713279500",
	},
}

Common["TuTuTuSahur"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://74338414415353",

	AnimationIds = {
		Idle = "rbxassetid://136232784990782",
	},
}

Common["TalpaDiFerro"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://131863892005390",

	AnimationIds = {
		Idle = "rbxassetid://77849382340820",
	},
}

Common["BambiniCrostini"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://103316911915108",

	AnimationIds = {
		Idle = "rbxassetid://77023161599070",
	},
}

Common["67"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://107322356914494",

	AnimationIds = {
		Idle = "rbxassetid://87480936207274",
	},
}

Common["BrBrBatabim"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://110739492947053",

	AnimationIds = {
		Idle = "rbxassetid://93165728041239",
	},
}

Common["TungTungTungSahur"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://124805610604876",

	AnimationIds = {
		Idle = "rbxassetid://124645936218589",
	},
}

Common["CappoccinoAssassino"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://100893586188508",

	AnimationIds = {
		Idle = "rbxassetid://79101502287160",
	},
}

Common["MelonOtter"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://119865150419102",

	AnimationIds = {
		Idle = "rbxassetid://78570754226359",
	},
}

Common["KiwiPipi"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://77497252012744",

	AnimationIds = {
		Idle = "rbxassetid://109504844715349",
	},
}

Common["FluriFlura"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://103695140537567",

	AnimationIds = {
		Idle = "rbxassetid://77592251144314",
	},
}

Common["GangsterFootera"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://113938563023841",

	AnimationIds = {
		Idle = "rbxassetid://126716733555377",
	},
}

Common["TrulimeroTruli"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://129279152020230",

	AnimationIds = {
		Idle = "rbxassetid://125089643092677",
	},
}

Common["TuTuTuSahur"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://74338414415353",

	AnimationIds = {
		Idle = "rbxassetid://136232784990782",
	},
}

Common["Dolphinita"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://127265047725576",

	AnimationIds = {
		Idle = "rbxassetid://77930713279500",
	},
}

Common["LaVaccaSaturnoSaturnita"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://80592685095531",

	AnimationIds = {
		Idle = "rbxassetid://136752188284966",
	},
}

Common["OrangutiniAnanasini"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://91997154021783",

	AnimationIds = {
		Idle = "rbxassetid://84587911706000",
	},
}

Common["CameloniMeleloni"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://122683656269557",

	AnimationIds = {
		Idle = "rbxassetid://134430181336684",
	},
}

Common["CocofantoElefanto"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://80530928986444",

	AnimationIds = {
		Idle = "rbxassetid://124265319224111",
	},
}

Common["GorilloWatermelondrillo"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://119858785379577",

	AnimationIds = {
		Idle = "rbxassetid://107547787295394",
	},
}

Common["Svinino"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://83119535216667",

	AnimationIds = {
		Idle = "rbxassetid://77895533680662",
	},
}

Common["GlorboFruittoDrillo"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://140159970776654",

	AnimationIds = {
		Idle = "rbxassetid://73222568054421",
	},
}

Common["BambiniCrostini"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://103316911915108",

	AnimationIds = {
		Idle = "rbxassetid://77023161599070",
	},
}

Common["Octopusini"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://93395440047745",

	AnimationIds = {
		Idle = "rbxassetid://126289974861159",
	},
}

Common["BrriBrriBicus"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid:// ",

	AnimationIds = {
		Idle = "rbxassetid://137403719232869",
	},
}

Common["LioneliCactusini"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://129184262592207",

	AnimationIds = {
		Idle = "rbxassetid://80043289823481",
	},
}

Common["AvocadiniAntilopini"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://140636033194438",

	AnimationIds = {
		Idle = "rbxassetid://71330596592635",
	},
}

Common["TricTracBaraboom"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://117980014441939",

	AnimationIds = {
		Idle = "rbxassetid://117287110682938",
	},
}

Common["BanditoBobritto"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://100365821558669",

	AnimationIds = {
		Idle = "rbxassetid://89070989402182",
	},
}

Common["TimCheese"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://113029366638482",

	AnimationIds = {
		Idle = "rbxassetid://83370059939481",
	},
}

Common["TalpaDiFerro"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://131863892005390",

	AnimationIds = {
		Idle = "rbxassetid://77849382340820",
	},
}

Common["PipeMan"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://134349231323811",

	AnimationIds = {
		Idle = "rbxassetid://117236878782608",
	},
}

Common["KiwiBird"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://75083833944999",

	AnimationIds = {
		Idle = "rbxassetid://123992322727377",
	},
}

Common["SickPenguin"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://70810466174755",

	AnimationIds = {
		Idle = "rbxassetid://83602497955243",
	},
}

Common["NoobiniPizzanini"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://71606418170750",

	AnimationIds = {
		Idle = "rbxassetid://113005956942330",
	},
}

Common["LaVacaSaturno"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://111451206983373",

	AnimationIds = {
		Idle = "rbxassetid://133817882690900",
	},
}

Common["JobApplication"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://92046509880592",

	AnimationIds = {
		Idle = "rbxassetid://132985846821600",
	},
}

Common["BallerinaCappuccina"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://81494017076106",

	AnimationIds = {
		Idle = "rbxassetid://87884903426823",
	},
}

Common["StrawberryElefant"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://97854959031588",

	AnimationIds = {
		Idle = "rbxassetid://81656321711623",
	},
}

Common["SpiderSammy"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://82549141631382",

	AnimationIds = {
		Idle = "rbxassetid://82205974184457",
	},
}

Common["Karkirkurkarkarkar"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://89982415178084",

	AnimationIds = {
		Idle = "rbxassetid://130542839858955",
	},
}

Common["HotSpot"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://111472700264743",

	AnimationIds = {
		Idle = "rbxassetid://106451101904928",
	},
}

Common["TVWorldini"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://119521413794917",

	AnimationIds = {
		Idle = "rbxassetid://73049896079264",
	},
}

Common["Pencile"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://82278819003740",

	AnimationIds = {
		Idle = "rbxassetid://71994850510316",
	},
}

Common["HotSpotBurittini"] = {
	IncomeRate = 10,
	Rarity = "Common",
	SpawnWeight = 50,
	Icon = "rbxassetid://105297272536700",

	AnimationIds = {
		Idle = "rbxassetid://98354941721705",
	},
}

return Common
