local Epic = {}

Epic["ChimpanziniBananini"] = {
	IncomeRate = 10,
	Rarity = "Epic",
	SpawnWeight = 50,
	Icon = "rbxassetid://73205751201522",

	AnimationIds = {
		Idle = "rbxassetid://869871724554912",
	},
}

Epic["BombardiniCrocodilo"] = {
	IncomeRate = 10,
	Rarity = "Epic",
	SpawnWeight = 50,
	Icon = "rbxassetid://119650527064413",

	AnimationIds = {
		Idle = "rbxassetid://124347462714625",
	},
}

Epic["LaVacaSaturno"] = {
	IncomeRate = 10,
	Rarity = "Epic",
	SpawnWeight = 50,
	Icon = "rbxassetid://111451206983373",

	AnimationIds = {
		Idle = "rbxassetid://133817882690900",
	},
}

Epic["Nuclearini"] = {
	IncomeRate = 10,
	Rarity = "Epic",
	SpawnWeight = 50,
	Icon = "rbxassetid://131606141302581",

	AnimationIds = {
		Idle = "rbxassetid://112074278378193",
	},
}

Epic["HotSpot"] = {
	IncomeRate = 10,
	Rarity = "Epic",
	SpawnWeight = 50,
	Icon = "rbxassetid://111472700264743",

	AnimationIds = {
		Idle = "rbxassetid://106451101904928",
	},
}

Epic["HotSpotBurittini"] = {
	IncomeRate = 10,
	Rarity = "Epic",
	SpawnWeight = 50,
	Icon = "rbxassetid://105297272536700",

	AnimationIds = {
		Idle = "rbxassetid://98354941721705",
	},
}

Epic["CocofantoElefanto"] = {
	IncomeRate = 10,
	Rarity = "Epic",
	SpawnWeight = 50,
	Icon = "rbxassetid://80530928986444",

	AnimationIds = {
		Idle = "rbxassetid://124265319224111",
	},
}

Epic["Pencile"] = {
	IncomeRate = 10,
	Rarity = "Epic",
	SpawnWeight = 50,
	Icon = "rbxassetid://82278819003740",

	AnimationIds = {
		Idle = "rbxassetid://71994850510316",
	},
}

Epic["RhinoToasterino"] = {
	IncomeRate = 10,
	Rarity = "Epic",
	SpawnWeight = 50,
	Icon = "rbxassetid://84387779182450",

	AnimationIds = {
		Idle = "rbxassetid://121256607735090",
	},
}

return Epic
