local Legendary = {}

Legendary["67"] = {
	IncomeRate = 10,
	Rarity = "Legendary",
	SpawnWeight = 50,
	Icon = "rbxassetid://107322356914494",

	AnimationIds = {
		Idle = "rbxassetid://87480936207274",
	},
}

Legendary["TralaleroTralala"] = {
	IncomeRate = 10,
	Rarity = "Legendary",
	SpawnWeight = 50,
	Icon = "rbxassetid://138992981777558",

	AnimationIds = {
		Idle = "rbxassetid://101827127902246",
	},
}

Legendary["LaVaccaSaturnoSaturnita"] = {
	IncomeRate = 10,
	Rarity = "Legendary",
	SpawnWeight = 50,
	Icon = "rbxassetid://80592685095531",

	AnimationIds = {
		Idle = "rbxassetid://136752188284966",
	},
}

Legendary["StrawberryElefant"] = {
	IncomeRate = 10,
	Rarity = "Legendary",
	SpawnWeight = 50,
	Icon = "rbxassetid://97854959031588",

	AnimationIds = {
		Idle = "rbxassetid://81656321711623",
	},
}

Legendary["TVWorldini"] = {
	IncomeRate = 10,
	Rarity = "Legendary",
	SpawnWeight = 50,
	Icon = "rbxassetid://119521413794917",

	AnimationIds = {
		Idle = "rbxassetid://73049896079264",
	},
}

return Legendary
