local Rare = {}

Rare["LiriliLarila"] = {
	IncomeRate = 10,
	Rarity = "Rare",
	SpawnWeight = 50,
	Icon = "rbxassetid://89008368620221",

	AnimationIds = {
		Idle = "rbxassetid://103192330142474",
	},
}

Rare["CappoccinoAssassino"] = {
	IncomeRate = 10,
	Rarity = "Rare",
	SpawnWeight = 50,
	Icon = "rbxassetid://100893586188508",

	AnimationIds = {
		Idle = "rbxassetid://79101502287160",
	},
}

Rare["BrBrBatabim"] = {
	IncomeRate = 10,
	Rarity = "Rare",
	SpawnWeight = 50,
	Icon = "rbxassetid://110739492947053",

	AnimationIds = {
		Idle = "rbxassetid://93165728041239",
	},
}

Rare["TungTungTungSahur"] = {
	IncomeRate = 10,
	Rarity = "Rare",
	SpawnWeight = 50,
	Icon = "rbxassetid://124805610604876",

	AnimationIds = {
		Idle = "rbxassetid://124645936218589",
	},
}

Rare["AvocadiniAntilopini"] = {
	IncomeRate = 10,
	Rarity = "Rare",
	SpawnWeight = 50,
	Icon = "rbxassetid://140636033194438",

	AnimationIds = {
		Idle = "rbxassetid://71330596592635",
	},
}

Rare["LioneliCactusini"] = {
	IncomeRate = 10,
	Rarity = "Rare",
	SpawnWeight = 50,
	Icon = "rbxassetid://129184262592207",

	AnimationIds = {
		Idle = "rbxassetid://80043289823481",
	},
}

Rare["GlorboFruittoDrillo"] = {
	IncomeRate = 10,
	Rarity = "Rare",
	SpawnWeight = 50,
	Icon = "rbxassetid://140159970776654",

	AnimationIds = {
		Idle = "rbxassetid://73222568054421",
	},
}

Rare["OrangutiniAnanasini"] = {
	IncomeRate = 10,
	Rarity = "Rare",
	SpawnWeight = 50,
	Icon = "rbxassetid://91997154021783",

	AnimationIds = {
		Idle = "rbxassetid://84587911706000",
	},
}

Rare["GorilloWatermelondrillo"] = {
	IncomeRate = 10,
	Rarity = "Rare",
	SpawnWeight = 50,
	Icon = "rbxassetid://119858785379577",

	AnimationIds = {
		Idle = "rbxassetid://107547787295394",
	},
}

Rare["ChicleteiraBicicleteira"] = {
	IncomeRate = 10,
	Rarity = "Rare",
	SpawnWeight = 50,
	Icon = "rbxassetid://108255901760618",

	AnimationIds = {
		Idle = "rbxassetid://75793055069842",
	},
}

Rare["UdinDinDinDun"] = {
	IncomeRate = 10,
	Rarity = "Rare",
	SpawnWeight = 50,
	Icon = "rbxassetid://110053801950744",

	AnimationIds = {
		Idle = "rbxassetid://104207278056799",
	},
}

Rare["BallerinaCappuccina"] = {
	IncomeRate = 10,
	Rarity = "Rare",
	SpawnWeight = 50,
	Icon = "rbxassetid://81494017076106",

	AnimationIds = {
		Idle = "rbxassetid://87884903426823",
	},
}

Rare["BombardiniGusini"] = {
	IncomeRate = 10,
	Rarity = "Rare",
	SpawnWeight = 50,
	Icon = "rbxassetid://139334967110097",

	AnimationIds = {
		Idle = "rbxassetid://94300113969778",
	},
}

return Rare
