local Uncommon = {}

Uncommon["TrippiTroppi"] = {
	IncomeRate = 10,
	Rarity = "Uncommon",
	SpawnWeight = 50,
	Icon = "rbxassetid://87972913009568",

	AnimationIds = {
		Idle = "rbxassetid://100097781969712",
	},
}

Uncommon["GangsterFootera"] = {
	IncomeRate = 10,
	Rarity = "Uncommon",
	SpawnWeight = 50,
	Icon = "rbxassetid://113938563023841",

	AnimationIds = {
		Idle = "rbxassetid://126716733555377",
	},
}

Uncommon["BanditoBobritto"] = {
	IncomeRate = 10,
	Rarity = "Uncommon",
	SpawnWeight = 50,
	Icon = "rbxassetid://100365821558669",

	AnimationIds = {
		Idle = "rbxassetid://89070989402182",
	},
}

Uncommon["BonecaAmbalabu"] = {
	IncomeRate = 10,
	Rarity = "Uncommon",
	SpawnWeight = 50,
	Icon = "rbxassetid://135833570114494",

	AnimationIds = {
		Idle = "rbxassetid://122330045939369",
	},
}

Uncommon["TricTracBaraboom"] = {
	IncomeRate = 10,
	Rarity = "Uncommon",
	SpawnWeight = 50,
	Icon = "rbxassetid://117980014441939",

	AnimationIds = {
		Idle = "rbxassetid://117287110682938",
	},
}

Uncommon["TrulimeroTruli"] = {
	IncomeRate = 10,
	Rarity = "Uncommon",
	SpawnWeight = 50,
	Icon = "rbxassetid://129279152020230",

	AnimationIds = {
		Idle = "rbxassetid://125089643092677",
	},
}

Uncommon["BrriBrriBicus"] = {
	IncomeRate = 10,
	Rarity = "Uncommon",
	SpawnWeight = 50,
	Icon = "rbxassetid://135369613991000",

	AnimationIds = {
		Idle = "rbxassetid://137403719232869",
	},
}

Uncommon["Octopusini"] = {
	IncomeRate = 10,
	Rarity = "Uncommon",
	SpawnWeight = 50,
	Icon = "rbxassetid://93395440047745",

	AnimationIds = {
		Idle = "rbxassetid://126289974861159",
	},
}

Uncommon["CameloniMeleloni"] = {
	IncomeRate = 10,
	Rarity = "Uncommon",
	SpawnWeight = 50,
	Icon = "rbxassetid://122683656269557",

	AnimationIds = {
		Idle = "rbxassetid://134430181336684",
	},
}

Uncommon["SpiderSammy"] = {
	IncomeRate = 10,
	Rarity = "Uncommon",
	SpawnWeight = 50,
	Icon = "rbxassetid://82549141631382",

	AnimationIds = {
		Idle = "rbxassetid://82205974184457",
	},
}

Uncommon["Karkirkurkarkarkar"] = {
	IncomeRate = 10,
	Rarity = "Uncommon",
	SpawnWeight = 50,
	Icon = "rbxassetid://89982415178084",

	AnimationIds = {
		Idle = "rbxassetid://130542839858955",
	},
}

Uncommon["FrigoCamelo"] = {
	IncomeRate = 10,
	Rarity = "Uncommon",
	SpawnWeight = 50,
	Icon = "rbxassetid://124682482052885",

	AnimationIds = {
		Idle = "rbxassetid://115954017666163",
	},
}

return Uncommon
