return {
	Default = {
		Weight = 98,
		Multiplier = 1,
		Color = Color3.fromRGB(211, 211, 211),
	},

	Golden = {
		Weight = 50,
		Multiplier = 2,
		Color = Color3.fromRGB(255, 174, 0),
		CoverImage = "rbxassetid://108836340890473",
	},

	Toxic = {
		Weight = 25,
		Multiplier = 2,
		Color = Color3.fromRGB(136, 255, 0),
		CoverImage = "rbxassetid://108836340890473",
	},

	Bloodmoon = {
		Weight = 10,
		Multiplier = 2,
		Color = Color3.fromRGB(255, 0, 85),
		CoverImage = "rbxassetid://108836340890473",
	},

	Void = {
		Weight = 0,
		Multiplier = 4,
		Color = Color3.fromRGB(68, 0, 255),
		CoverImage = "rbxassetid://131105216546517",
	},
}
